backend:
  name: git-gateway
  branch: main

media_folder: "static/assets/img/games"
public_folder: "/assets/img/games"

collections:
  - name: "games"
    label: "Games"
    label_singular: "Game"
    folder: "content/games"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Note", name: "note", required: false, widget: "string"}
      - {label: "Platform", name: "platform", widget: "relation", collection: "_platforms", value_field: "slug", display_fields: ["title"], search_fields: ["title"], options_length: 100}
      - {label: "Genre", name: "genre", widget: "relation", collection: "_genres", value_field: "slug", display_fields: ["title"], search_fields: ["title"], multiple: true, options_length: 100}
      - {label: "Physical", name: "physical", required: false, default: false, widget: "boolean"}
      - {label: "Digital", name: "digital", required: false, default: false, widget: "boolean"}
      - {label: "Guide", name: "guide", required: false, default: false, widget: "boolean"}
      - {label: "Pending", name: "pending", required: false, default: false, widget: "boolean"}
      - {label: "Posted", name: "posted", widget: "date", default: "YYYY-MM-DD", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
  - name: "systems"
    label: "Systems"
    label_singular: "System"
    folder: "content/systems"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Platform", name: "platform", widget: "relation", collection: "_platforms", value_field: "slug", display_fields: ["title"], search_fields: ["title"], options_length: 100}
      - {label: "System Type", name: "system_type", widget: "select", options: [{label: "Console", value: "console"}, {label: "Handheld", value: "handheld"}, {label: "Hybrid", value: "hybrid"}, {label: "Mini", value: "mini"}]}
      - {label: "Variation", name: "variation", required: false, widget: "string"}
      - {label: "Accessories", name: "accessories", required: false, widget: "string"}
  - name: "controllers"
    label: "Controllers"
    label_singular: "Controller"
    folder: "content/controllers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Variation", name: "variation", required: false, widget: "string"}
      - {label: "Connection", name: "connection", required: false, widget: "string"}
      - {label: "Company", name: "company", widget: "select", options: ["8Bitdo", "Bandai", "HORI", "Junkfood Custom Arcades", "Logitech", "Polymega", "Retro-Bit", "Retro Fighters", "Sammy", "Wind Spirit", "Wish Technologies"]}
  - name: "_platforms"
    label: "Platforms"
    label_singular: "Platform"
    folder: "content/_platform"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Logo", name: "logo", required: false, widget: "code", default_language: 'svg', output_code_only: true}
      - {label: "Disc", name: "disc", required: false, widget: "boolean"}
      - {label: "Cartridge", name: "cartridge", required: false, widget: "boolean"}
      - {label: "Color", name: "color", required: false, widget: "string"}
      - {label: "Order", name: "order", required: false, widget: "number"}
  - name: "_genres"
    label: "Genres"
    label_singular: "Genre"
    folder: "content/_genre"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']}
      - {label: "Icon", name: "icon", widget: "string"}